/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.9/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

rootProject.name = "faculty_day"
include("lesson01")
include("lesson02")
include("lesson03")
include("lesson04")
include("lesson05")
include("lesson06")
include("lesson07")
include("lesson08")
include("lesson09")
include("lesson10")
include("lesson11")
include("lesson12")
include("lesson13")
include("lesson14")
include("lesson15")
include("lesson16")
include("lesson17")