-- ============================================================================
-- ЗАДАНИЕ ФИНАЛ: Создать таблицу readers
-- ============================================================================

create table readers (
    id bigint generated by default as identity primary key,
    name varchar(128),
    email varchar(128)
);

create table mm_readers_book (
    reader_id bigint not null,
    book_id bigint not null,

    // ТИПО УМНЫЙ :)
    primary key (reader_id, book_id),
    foreign key (reader_id) references readers(id),
    foreign key (book_id) references books(id)
);

// HOMEWORK TEST DATA
INSERT INTO readers (name, email) VALUES
    ('Иван Петров', 'ivan.petrov@example.com'),
    ('Мария Смирнова', 'maria.smirnova@example.com'),
    ('Алексей Волков', 'alexey.volkov@example.com'),
    ('Екатерина Лебедева', 'ekaterina.lebedeva@example.com'),
    ('Даниил Морозов', 'danil.morozov@example.com');

INSERT INTO mm_readers_book (reader_id, book_id) VALUES
    (1, 1),
    (1, 5),
    (2, 3),
    (2, 4),
    (3, 2),
    (3, 7),
    (4, 6),
    (4, 1),
    (5, 5),
    (5, 7);